# Generated by Django 5.2.7 on 2025-10-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='remove_profile_picture',
            field=models.BooleanField(default=False),
        ),
    ]
