# Generated by Django 5.2.7 on 2025-10-16 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_userprofile_remove_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='remove_profile_picture',
        ),
    ]
