# Generated by Django 5.2.7 on 2025-10-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
