# Generated by Django 5.2.7 on 2025-10-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_jobpost_polloption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='requirements',
            new_name='benefits',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='application_url',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='salary',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='application_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary_range',
            field=models.CharField(blank=True, choices=[('0-30k', '$0 - $30,000'), ('30k-50k', '$30,000 - $50,000'), ('50k-80k', '$50,000 - $80,000'), ('80k-120k', '$80,000 - $120,000'), ('120k+', '$120,000+'), ('negotiable', 'Negotiable')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='skills_required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='work_mode',
            field=models.CharField(choices=[('onsite', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('flexible', 'Flexible')], default='onsite', max_length=20),
        ),
    ]
