# Generated by Django 5.2.7 on 2025-10-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_requirements_jobpost_benefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('poll', 'Poll'), ('job', 'Job Offer')], max_length=10),
        ),
    ]
