# Generated by Django 5.2.7 on 2025-10-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='type',
            new_name='reaction_type',
        ),
    ]
