# Generated by Django 5.2.7 on 2025-10-29 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_type_reaction_reaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polloption',
            name='votes',
        ),
        migrations.AddField(
            model_name='polloption',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voted_options', to=settings.AUTH_USER_MODEL),
        ),
    ]
