# Generated by Django 5.2.7 on 2025-10-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_polloption_votes_polloption_voters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polloption',
            name='voters',
        ),
        migrations.AddField(
            model_name='polloption',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
