# Generated by Django 5.2.7 on 2025-10-29 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_polloption_voters_polloption_votes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polloption',
            options={},
        ),
        migrations.AddField(
            model_name='polloption',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voted_options', to=settings.AUTH_USER_MODEL),
        ),
    ]
