# Generated by Django 5.2.7 on 2025-10-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_polloption_options_polloption_voters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('job', 'Job Offer')], max_length=10),
        ),
        migrations.DeleteModel(
            name='PollOption',
        ),
    ]
