# Generated by Django 5.2.7 on 2025-10-29 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_shared_post_share'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
