# Generated by Django 5.2.9 on 2026-01-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_alter_notification_notification_type_mention'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mention',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mention', 'verbose_name_plural': 'Mentions'},
        ),
        migrations.AlterField(
            model_name='mention',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Position in the text where mention occurs'),
        ),
    ]
