# Generated by Django 5.2.7 on 2025-11-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboration',
            name='collaborator',
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='following_count',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='total_comments',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='total_likes',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='total_posts',
        ),
        migrations.DeleteModel(
            name='AdCampaign',
        ),
        migrations.DeleteModel(
            name='Collaboration',
        ),
    ]
