# Generated by Django 5.2.7 on 2025-12-01 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_remove_collaboration_collaborator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='creatorprofile',
            old_name='join_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='verified_date',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='engagement_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='total_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='total_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creatorprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
