# Generated by Django 5.2.7 on 2025-12-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0003_rename_join_date_creatorprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
