services:
  - type: web
    name: talentforge-amira
    env: python
    region: oregon
    plan: free
    rootDir: talentForge
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn talentForge.wsgi:application
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
    autoDeploy: true

databases:
  - name: talentforge-db
    plan: free